package com.hankkin.reading.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hankkin.reading.domain.User;
import com.hankkin.reading.domain.HotBean;

import com.hankkin.reading.greendao.UserDao;
import com.hankkin.reading.greendao.HotBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig hotBeanDaoConfig;

    private final UserDao userDao;
    private final HotBeanDao hotBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        hotBeanDaoConfig = daoConfigMap.get(HotBeanDao.class).clone();
        hotBeanDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        hotBeanDao = new HotBeanDao(hotBeanDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(HotBean.class, hotBeanDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        hotBeanDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HotBeanDao getHotBeanDao() {
        return hotBeanDao;
    }

}
